# Generated by Django 5.0.4 on 2024-05-15 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_remove_event_created_at_remove_event_updated_at_and_more"),
        ("invitations", "0005_remove_invitation_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.UniqueConstraint(
                fields=("attendee", "event"),
                name="invitations_invitation_unique_pair_of_attendee_and_event",
                violation_error_message="This user already has an invitation to the event.",
            ),
        ),
    ]
